fail_on_violations: true

scss:
  enable: false

jshint:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc

ruby:
  enabled: false

sass-lint:
  enabled: true
  config_file: .sass-lint.yml
