rules:
  property-sort-order:
    - 2
    - order: 'smacss'
  force-element-nesting:
    - 0
  class-name-format:
    - 0
  no-color-literals:
    - 2
    -
      allow-rgba: true
  no-url-protocols:
    - 0
  class-name-format:
    -
      allow-leading-underscore: false
  nesting-depth:
    - 8
    -
      max-depth: 3
  no-vendor-prefixes: 0
